### ISSUE TITLE
Add functionality to manage shares

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-samba#5]
It would be nice if I could add variables like:

```yaml
samba_shares:
  - name: example
    options: |
      create mask = 0777
      directory mask = 0777
```

Something along those lines (at a minimum), and it would output in `/etc/samba/smb.conf`:

```
[example]
   create mask = 0777
   directory mask = 0777
```

(Just as an example).
